### ISSUE TITLE
ROLDAN URIEL ARCADIO AVILA INFOGRAFIA 1BS

### ISSUE THREAD

**Issue by Roldanuriel** [SistemasTecTlaxiaco/actividad-2-infografia-Roldanuriel#1]
[ROLDAN URIEL ARCADIO AVILA 1BS INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-Roldanuriel/files/9460058/ROLDAN.URIEL.ARCADIO.AVILA.1BS.INFOGRAFIA.pdf)

**Comment by Jaczibeth** [comment]
de 20% tuviste 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
